#!/bin/bash
export CATALINA_OPTS="-XX:MaxPermSize=256m -Xmx4096m -Xms256m -server -Drdeck.base=/data/1/apps/rundeck-base -Drundeck.config.location=/data/1/apps/rundeck-base/rundeck-config.properties"
/data/1/apps/apache-tomcat/bin/startup.sh